import {
  ChartCandlestick,
  LayoutDashboard,
  TicketSlash,
  SquarePlus,
  Notebook,
  NotebookPen,
} from "lucide-react";

import {
  AssetCategoryDetail,
  AssetNumberClassDetail,
  AssetNumberDetail,
  AssetNumberSubclassDetail,
  AssetStateDetail,
  NavLinkDetail,
} from "../Types/Types";


// Helper function to generate a unique random number within a specific range
function generateUniqueRandomNumbers(
  count: number,
  min: number,
  max: number
): number[] {
  const uniqueNumbers = new Set<number>();

  while (uniqueNumbers.size < count) {
    const randomNumber = Math.floor(Math.random() * (max - min + 1)) + min;
    uniqueNumbers.add(randomNumber);
  }

  return Array.from(uniqueNumbers);
}

// Get the unique idfex values
const uniqueIdfexValues = generateUniqueRandomNumbers(15, 10000, 99999); // Adjust range as needed

// Your navLinks array with numeric IDs
export const navLinks: NavLinkDetail[] = [
  {
    id: 1,
    label: "لوحة التحكم",
    route: "/",
    icon: LayoutDashboard,
    visible: ["admin"],
  },
  {
    id: 2,
    label: "الاصول",
    route: "/assets",
    icon: ChartCandlestick,
    visible: ["admin", "odoo"],
  },
  {
    id: 3,
    label: "اضافة اصل لأودو",
    route: "/assets/create",
    icon: SquarePlus,
    visible: ["admin", "odoo"],
  },
  {
    id: 4,
    label: "الجرد",
    route: "/assetInventory",
    icon: TicketSlash,
    visible: ["admin", "user"],
  },
  {
    id: 5,
    label: "اضافة اصل لجرد",
    route: "/assetInventory/new",
    icon: SquarePlus,
    visible: ["admin", "user"],
  },
  {
    id: 6,
    label: "ملاحظات",
    route: "/noteis",
    icon: Notebook,
    visible: ["admin"],
  },
  {
    id: 7,
    label: "اضف ملاحظة",
    route: "/noteis/new",
    icon: NotebookPen,
    visible: ["admin", "noter", "user"],
  },
  // Add more pages as needed
];

// asset_Number_class
export const asset_State: AssetStateDetail[] = [
  { id: 1, label: "جديد", value: "new" },
  { id: 2, label: "مستعمل", value: "used" },
  { id: 3, label: "عاطل", value: "damaged" },
];

export const asset_category: AssetCategoryDetail[] = [
  { id: 1, label: "مبانى", value: "buildings" },
  { id: 2, label: "وسائل نقل", value: "transportation" },
  { id: 3, label: "وسائل نقل البضاعة", value: "cargo" },
  { id: 4, label: "اثاث", value: "furniture" },
  { id: 5, label: "الات", value: "machines" },
];

export const columnNamesSearch: Record<string, string> = {
  name: "اسم الاصل",
  place_of_asset: "مكان الأصل",
  name_of_recepiet: "اسم مستلم الاصل",
  pin: "رقم الوظيفي",
};

export const columnNamesView: Record<string, string> = {
  asset_tags: "تاغ الاصل",
  asset_status: "حالة الاصل",
  asset_number_1: "رقم تصنيف الاساسي ",
  asset_number_2: "رقم تصنيف فرعي",
  asset_number_3: "رقم تصنيف تفصيلي",
  asset_number_4: "رقم تعريفي لاصل ",
  asset_combined_number: "رقم الاصل",
  original_value: "قيمة الأصل",
  place_of_asset: "مكان الأصل",
  name_of_recepiet: "اسم مستلم الاصل",
  pin: "رقم الوظيفي",
  using_date: "تاريخ استلام الأصل",
};

export const asset_Number_class: AssetNumberClassDetail[] = [
  { id: 1, idfex: uniqueIdfexValues[0], label: "المباني", value: "1" },
  { id: 2, idfex: uniqueIdfexValues[1], label: "المعدات البحرية", value: "2" },
  { id: 3, idfex: uniqueIdfexValues[2], label: "المعدات البرية", value: "3" },
  { id: 4, idfex: uniqueIdfexValues[3], label: "وسائل نقل", value: "4" },
  { id: 5, idfex: uniqueIdfexValues[4], label: "معدات الورش", value: "5" },
  { id: 6, idfex: uniqueIdfexValues[5], label: "أثاث مكتبي", value: "6" },
  {
    id: 7,
    idfex: uniqueIdfexValues[6],
    label: "معدات وأدوات مكتبية",
    value: "7",
  },
  { id: 8, idfex: uniqueIdfexValues[7], label: "الأراضي", value: "8" },
  { id: 9, idfex: uniqueIdfexValues[8], label: "معدات الصومعة", value: "9" },
  { id: 10, idfex: uniqueIdfexValues[9], label: "الأرصفة", value: "10" },
  {
    id: 11,
    idfex: uniqueIdfexValues[10],
    label: "الطرق والساحات",
    value: "11",
  },
  { id: 12, idfex: uniqueIdfexValues[11], label: "حواجز الأمواج", value: "12" },
  { id: 13, idfex: uniqueIdfexValues[12], label: "معدات ومحطات", value: "13" },
  {
    id: 14,
    idfex: uniqueIdfexValues[13],
    label: "الأصول غير ملموسة",
    value: "14",
  },
  { id: 15, idfex: uniqueIdfexValues[14], label: "المخرد", value: "15" },
];

export const asset_Number_subclass: AssetNumberSubclassDetail[] = [
  // المباني
  {
    id: 1,
    idfex: 13,
    label: "المباني",
    value: "1",
    asset_Number_class: "1",
  },
  {
    id: 2,
    idfex: 14,
    label: "المنصات",
    value: "2",
    asset_Number_class: "1",
  },
  {
    id: 3,
    idfex: 15,
    label: "مصاعد",
    value: "3",
    asset_Number_class: "1",
  },
  {
    id: 4,
    idfex: 16,
    label: "الطرق",
    value: "4",
    asset_Number_class: "1",
  },
  {
    id: 5,
    idfex: 17,
    label: "شبكات المياه",
    value: "5",
    asset_Number_class: "1",
  },
  {
    id: 6,
    idfex: 18,
    label: "الانشاءات",
    value: "6",
    asset_Number_class: "1",
  },
  {
    id: 9,
    idfex: 19,
    label: "محطات",
    value: "9",
    asset_Number_class: "1",
  },
  {
    id: 10,
    idfex: 20,
    label: "البوابات",
    value: "10",
    asset_Number_class: "1",
  },
  {
    id: 11,
    idfex: 21,
    label: "مظلات",
    value: "11",
    asset_Number_class: "1",
  },

  // المعدات البحرية
  {
    id: 12,
    idfex: 22,
    label: "القواطر",
    value: "1",
    asset_Number_class: "2",
  },
  {
    id: 13,
    idfex: 23,
    label: "الزوارق",
    value: "2",
    asset_Number_class: "2",
  },
  {
    id: 14,
    idfex: 24,
    label: "الروافع",
    value: "3",
    asset_Number_class: "2",
  },
  {
    id: 15,
    idfex: 25,
    label: "المنارات",
    value: "4",
    asset_Number_class: "2",
  },

  // المعدات البرية
  {
    id: 16,
    idfex: 26,
    label: "شوكية",
    value: "1",
    asset_Number_class: "3",
  },
  {
    id: 17,
    idfex: 27,
    label: "يدوية",
    value: "2",
    asset_Number_class: "3",
  },
  {
    id: 18,
    idfex: 28,
    label: "ارضية",
    value: "3",
    asset_Number_class: "3",
  },
  {
    id: 19,
    idfex: 29,
    label: "غرافات",
    value: "4",
    asset_Number_class: "3",
  },
  {
    id: 20,
    idfex: 30,
    label: "شفاطات",
    value: "5",
    asset_Number_class: "3",
  },
  {
    id: 21,
    idfex: 31,
    label: "جرارات",
    value: "6",
    asset_Number_class: "3",
  },
  {
    id: 22,
    idfex: 32,
    label: "مقطورات",
    value: "7",
    asset_Number_class: "3",
  },
  {
    id: 23,
    idfex: 33,
    label: "خزانات",
    value: "8",
    asset_Number_class: "3",
  },
  {
    id: 24,
    idfex: 34,
    label: "معدات مناولة",
    value: "9",
    asset_Number_class: "3",
  },
  {
    id: 25,
    idfex: 35,
    label: "الالات",
    value: "10",
    asset_Number_class: "3",
  },
  {
    id: 26,
    idfex: 36,
    label: "الموازين",
    value: "11",
    asset_Number_class: "3",
  },
  {
    id: 27,
    idfex: 37,
    label: "محطات كهرباء",
    value: "12",
    asset_Number_class: "3",
  },
  {
    id: 28,
    idfex: 38,
    label: "مدات محطة مالجة ال الحي",
    value: "13",
    asset_Number_class: "3",
  },
  {
    id: 29,
    idfex: 39,
    label: "مدات والالاي الومة",
    value: "14",
    asset_Number_class: "3",
  },
  {
    id: 30,
    idfex: 40,
    label: "ابراج",
    value: "15",
    asset_Number_class: "3",
  },
  {
    id: 31,
    idfex: 41,
    label: "قنطرية",
    value: "16",
    asset_Number_class: "3",
  },
  {
    id: 32,
    idfex: 42,
    label: "شاحنات",
    value: "17",
    asset_Number_class: "3",
  },

  // وسائل نقل
  {
    id: 33,
    idfex: 43,
    label: "صالون",
    value: "1",
    asset_Number_class: "4",
  },
  {
    id: 34,
    idfex: 44,
    label: "نقل مزدوج",
    value: "2",
    asset_Number_class: "4",
  },
  {
    id: 35,
    idfex: 45,
    label: "نقل خفيف",
    value: "3",
    asset_Number_class: "4",
  },
  {
    id: 36,
    idfex: 46,
    label: "حافلات",
    value: "4",
    asset_Number_class: "4",
  },
  {
    id: 37,
    idfex: 47,
    label: "شاحنة بضائع",
    value: "5",
    asset_Number_class: "4",
  },
  {
    id: 38,
    idfex: 48,
    label: "ناقلات",
    value: "6",
    asset_Number_class: "4",
  },
  {
    id: 39,
    idfex: 49,
    label: "اسعاف",
    value: "7",
    asset_Number_class: "4",
  },
  {
    id: 40,
    idfex: 50,
    label: "مطافي",
    value: "8",
    asset_Number_class: "4",
  },
  {
    id: 41,
    idfex: 51,
    label: "درجات",
    value: "9",
    asset_Number_class: "4",
  },
  {
    id: 42,
    idfex: 52,
    label: "سيارة مجهزة بعدة",
    value: "10",
    asset_Number_class: "4",
  },

  // معدات الورش
  {
    id: 43,
    idfex: 53,
    label: "الات ورش",
    value: "1",
    asset_Number_class: "5",
  },
  {
    id: 44,
    idfex: 54,
    label: "مضخات",
    value: "2",
    asset_Number_class: "5",
  },
  {
    id: 45,
    idfex: 55,
    label: "معدات سلامة",
    value: "3",
    asset_Number_class: "5",
  },
  {
    id: 46,
    idfex: 56,
    label: "الانارة",
    value: "4",
    asset_Number_class: "5",
  },
  {
    id: 47,
    idfex: 57,
    label: "معدات بحرية",
    value: "5",
    asset_Number_class: "5",
  },
  {
    id: 48,
    idfex: 58,
    label: "ضاغط هواء",
    value: "6",
    asset_Number_class: "5",
  },
  {
    id: 49,
    idfex: 59,
    label: "سلم",
    value: "7",
    asset_Number_class: "5",
  },
  {
    id: 50,
    idfex: 60,
    label: "متنوعة",
    value: "8",
    asset_Number_class: "5",
  },

  // أثاث مكتبي
  {
    id: 51,
    idfex: 61,
    label: "المكاتب والمكتبات",
    value: "1",
    asset_Number_class: "6",
  },
  {
    id: 52,
    idfex: 62,
    label: "كراسي ودواليب",
    value: "2",
    asset_Number_class: "6",
  },
  {
    id: 53,
    idfex: 63,
    label: "اثاث منزلي",
    value: "3",
    asset_Number_class: "6",
  },
  {
    id: 54,
    idfex: 64,
    label: "معدات طبية",
    value: "4",
    asset_Number_class: "6",
  },
  {
    id: 55,
    idfex: 65,
    label: "محدوفات",
    value: "22",
    asset_Number_class: "6",
  },

  // معدات وأدوات مكتبية
  {
    id: 56,
    idfex: 66,
    label: "معدات لاسلكي وهواتف",
    value: "1",
    asset_Number_class: "7",
  },
  {
    id: 57,
    idfex: 67,
    label: "حواسيب وفاكسات",
    value: "2",
    asset_Number_class: "7",
  },
  {
    id: 58,
    idfex: 68,
    label: "اجهزة ومعدات",
    value: "3",
    asset_Number_class: "7",
  },
  {
    id: 59,
    idfex: 69,
    label: "مكيفات",
    value: "4",
    asset_Number_class: "7",
  },
  {
    id: 60,
    idfex: 70,
    label: "أثاث",
    value: "5",
    asset_Number_class: "7",
  },

  // الأراضي
  {
    id: 61,
    idfex: 71,
    label: "أراضي زراعية",
    value: "1",
    asset_Number_class: "8",
  },
  {
    id: 62,
    idfex: 72,
    label: "أراضي سكنية",
    value: "2",
    asset_Number_class: "8",
  },
  {
    id: 63,
    idfex: 73,
    label: "أراضي صناعية",
    value: "3",
    asset_Number_class: "8",
  },

  // معدات الصومعة
  {
    id: 64,
    idfex: 74,
    label: "صومعة",
    value: "1",
    asset_Number_class: "9",
  },
  {
    id: 65,
    idfex: 75,
    label: "أجهزة ومعدات",
    value: "2",
    asset_Number_class: "9",
  },

  // الأرصفة
  {
    id: 66,
    idfex: 76,
    label: "أرصفة",
    value: "1",
    asset_Number_class: "10",
  },
  {
    id: 67,
    idfex: 77,
    label: "أرصفة مائية",
    value: "2",
    asset_Number_class: "10",
  },

  // الطرق والساحات
  {
    id: 68,
    idfex: 78,
    label: "طرق",
    value: "1",
    asset_Number_class: "11",
  },
  {
    id: 69,
    idfex: 79,
    label: "ساحات",
    value: "2",
    asset_Number_class: "11",
  },

  // حواجز الأمواج
  {
    id: 70,
    idfex: 80,
    label: "حواجز",
    value: "1",
    asset_Number_class: "12",
  },
  {
    id: 71,
    idfex: 81,
    label: "أعمدة إنارة",
    value: "2",
    asset_Number_class: "12",
  },

  // مولدات الطاقة
  {
    id: 72,
    idfex: 82,
    label: "مولدات",
    value: "1",
    asset_Number_class: "13",
  },
  {
    id: 73,
    idfex: 83,
    label: "محولات كهرباء",
    value: "2",
    asset_Number_class: "13",
  },

  // محطات معالجة مياه
  {
    id: 74,
    idfex: 84,
    label: "محطات",
    value: "1",
    asset_Number_class: "14",
  },
  {
    id: 75,
    idfex: 85,
    label: "خزانات",
    value: "2",
    asset_Number_class: "14",
  },

  // مواقف السيارات
  {
    id: 76,
    idfex: 86,
    label: "مواقف سيارات",
    value: "1",
    asset_Number_class: "15",
  },
];


export const asset_Number_detail: AssetNumberDetail[] = [
  {
    id: 1,
    idfex: 87,
    label: "خرسانة",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "1",
  },
  {
    id: 2,
    idfex: 88,
    label: "متنقلة",
    value: "2",
    asset_Number_class: "1",
    asset_Number_subclass: "1",
  },
  {
    id: 3,
    idfex: 89,
    label: "جاهزة",
    value: "3",
    asset_Number_class: "1",
    asset_Number_subclass: "1",
  },
  {
    id: 4,
    idfex: 90,
    label: "سياج",
    value: "4",
    asset_Number_class: "1",
    asset_Number_subclass: "1",
  },
  {
    id: 5,
    idfex: 91,
    label: "مخزن",
    value: "5",
    asset_Number_class: "1",
    asset_Number_subclass: "1",
  },
  {
    id: 6,
    idfex: 92,
    label: "منصات",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "2",
  },
  {
    id: 7,
    idfex: 93,
    label: "مضلات",
    value: "2",
    asset_Number_class: "1",
    asset_Number_subclass: "2",
  },
  {
    id: 8,
    idfex: 94,
    label: "مصعد حمولة 6 أشخاص",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "3",
  },
  {
    id: 9,
    idfex: 95,
    label: "الطرق",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "4",
  },
  {
    id: 10,
    idfex: 96,
    label: "ساحات",
    value: "2",
    asset_Number_class: "1",
    asset_Number_subclass: "4",
  },
  {
    id: 11,
    idfex: 97,
    label: "شبكات مياه",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "5",
  },
  {
    id: 12,
    idfex: 98,
    label: "انشاءات",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "6",
  },
  {
    id: 13,
    idfex: 99,
    label: "ساحات",
    value: "2",
    asset_Number_class: "1",
    asset_Number_subclass: "6",
  },
  {
    id: 14,
    idfex: 100,
    label: "الكهرباء",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "9",
  },
  {
    id: 15,
    idfex: 101,
    label: "الصرف الصحي",
    value: "2",
    asset_Number_class: "1",
    asset_Number_subclass: "9",
  },
  {
    id: 16,
    idfex: 102,
    label: "البوابات",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "10",
  },
  {
    id: 17,
    idfex: 103,
    label: "مظلات بالصاج",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "11",
  },
  {
    id: 18,
    idfex: 104,
    label: "مضلات قماش",
    value: "2",
    asset_Number_class: "1",
    asset_Number_subclass: "11",
  },
  {
    id: 19,
    idfex: 105,
    label: "قواطر",
    value: "1",
    asset_Number_class: "2",
    asset_Number_subclass: "1",
  },
  {
    id: 20,
    idfex: 106,
    label: "ناقلة مياه",
    value: "2",
    asset_Number_class: "2",
    asset_Number_subclass: "1",
  },
  {
    id: 21,
    idfex: 107,
    label: "ارشاد",
    value: "1",
    asset_Number_class: "2",
    asset_Number_subclass: "2",
  },
  {
    id: 22,
    idfex: 108,
    label: "مسح",
    value: "2",
    asset_Number_class: "2",
    asset_Number_subclass: "2",
  },
  {
    id: 23,
    idfex: 109,
    label: "ربط",
    value: "3",
    asset_Number_class: "2",
    asset_Number_subclass: "2",
  },
  {
    id: 24,
    idfex: 110,
    label: "قوارب",
    value: "4",
    asset_Number_class: "2",
    asset_Number_subclass: "2",
  },
  {
    id: 25,
    idfex: 111,
    label: "روافع",
    value: "1",
    asset_Number_class: "2",
    asset_Number_subclass: "3",
  },
  {
    id: 26,
    idfex: 112,
    label: "منارات",
    value: "1",
    asset_Number_class: "2",
    asset_Number_subclass: "4",
  },
  {
    id: 27,
    idfex: 113,
    label: "منارة بحرية",
    value: "2",
    asset_Number_class: "2",
    asset_Number_subclass: "4",
  },
  {
    id: 28,
    idfex: 114,
    label: "3 طن",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 29,
    idfex: 115,
    label: "7 طن",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 30,
    idfex: 116,
    label: "12 طن",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 31,
    idfex: 117,
    label: "16 طن",
    value: "4",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 32,
    idfex: 118,
    label: "30 طن",
    value: "5",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 33,
    idfex: 119,
    label: "40 طن",
    value: "6",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 34,
    idfex: 120,
    label: "36 طن",
    value: "7",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 35,
    idfex: 121,
    label: "13 طن",
    value: "8",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 36,
    idfex: 122,
    label: "45 طن",
    value: "9",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 37,
    idfex: 123,
    label: "65 طن",
    value: "10",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 38,
    idfex: 124,
    label: "شوكية",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "2",
  },
  {
    id: 39,
    idfex: 125,
    label: "يدوية",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "2",
  },
  {
    id: 40,
    idfex: 126,
    label: "ارضية",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "2",
  },
  {
    id: 41,
    idfex: 127,
    label: "ونش",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "3",
  },
  {
    id: 42,
    idfex: 128,
    label: "رافعة سلة",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "3",
  },
  {
    id: 43,
    idfex: 129,
    label: "رافعة بالسكة",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "3",
  },
  {
    id: 44,
    idfex: 130,
    label: "حفار",
    value: "4",
    asset_Number_class: "3",
    asset_Number_subclass: "3",
  },
  {
    id: 45,
    idfex: 131,
    label: "تسوية",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "4",
  },
  {
    id: 46,
    idfex: 132,
    label: "حبوب",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "4",
  },
  {
    id: 47,
    idfex: 133,
    label: "محوري",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "4",
  },
  {
    id: 48,
    idfex: 134,
    label: "نيرو",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "5",
  },
  {
    id: 49,
    idfex: 135,
    label: "فيقان",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "5",
  },
  {
    id: 50,
    idfex: 136,
    label: "جرار بضائع",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "6",
  },
  {
    id: 51,
    idfex: 137,
    label: "جرار زراعي",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "6",
  },
  {
    id: 52,
    idfex: 138,
    label: "بطاح",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 53,
    idfex: 139,
    label: "ترابوزة",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 54,
    idfex: 140,
    label: "واطي",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 55,
    idfex: 141,
    label: "ساحة",
    value: "4",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 56,
    idfex: 142,
    label: "زراعي",
    value: "5",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 57,
    idfex: 143,
    label: "مسطح",
    value: "6",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 58,
    idfex: 144,
    label: "صناعي",
    value: "7",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 59,
    idfex: 145,
    label: "محاور عجلات",
    value: "8",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 60,
    idfex: 146,
    label: "ثابت",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "8",
  },
  {
    id: 61,
    idfex: 147,
    label: "مجرور",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "8",
  },
  {
    id: 62,
    idfex: 148,
    label: "لاقط حاويات",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 63,
    idfex: 149,
    label: "منصة",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 64,
    idfex: 150,
    label: "مساند",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 65,
    idfex: 151,
    label: "ابراقة",
    value: "4",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 66,
    idfex: 152,
    label: "وعاء مناولة",
    value: "5",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 67,
    idfex: 153,
    label: "ملحق رافعة",
    value: "6",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 68,
    idfex: 154,
    label: "متدحرجة",
    value: "7",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 69,
    idfex: 155,
    label: "كماشة مناولة شاحنات",
    value: "8",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 70,
    idfex: 156,
    label: "اقماع",
    value: "9",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 71,
    idfex: 157,
    label: "متنوعة",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "10",
  },
  {
    id: 72,
    idfex: 158,
    label: "ميزان ارضي",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "11",
  },
  {
    id: 73,
    idfex: 159,
    label: "ميزان",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "11",
  },
  {
    id: 74,
    idfex: 160,
    label: "اثقال معايرة",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "11",
  },
  {
    id: 75,
    idfex: 161,
    label: "مفتاح الي",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "12",
  },
  {
    id: 76,
    idfex: 162,
    label: "محطات",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "12",
  },
  {
    id: 77,
    idfex: 163,
    label: "الف الحي",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "13",
  },
  {
    id: 78,
    idfex: 164,
    label: "مدات والالاي الومة",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "14",
  },
  {
    id: 79,
    idfex: 165,
    label: "كهبائية",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "15",
  },
  {
    id: 80,
    idfex: 166,
    label: "قنطرية",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "16",
  },
  {
    id: 81,
    idfex: 167,
    label: "شاحنة مجهزة بسلة صيانة",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "17",
  },
  {
    id: 82,
    idfex: 168,
    label: "فيات",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "17",
  },
  {
    id: 83,
    idfex: 169,
    label: "شاحنة مزودة بخزان",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "17",
  },
  {
    id: 84,
    idfex: 170,
    label: "شاحنة بصندوق قلاب",
    value: "4",
    asset_Number_class: "3",
    asset_Number_subclass: "17",
  },
  {
    id: 85,
    idfex: 171,
    label: "شاحنة افيكوا مع منظومة شفط",
    value: "5",
    asset_Number_class: "3",
    asset_Number_subclass: "17",
  },
  {
    id: 86,
    idfex: 172,
    label: "هونداي",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 87,
    idfex: 173,
    label: "داوو",
    value: "2",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 88,
    idfex: 174,
    label: "صني",
    value: "3",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 89,
    idfex: 175,
    label: "بيجو",
    value: "4",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 90,
    idfex: 176,
    label: "متشي بيشي",
    value: "5",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 91,
    idfex: 177,
    label: "باصات",
    value: "6",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 92,
    idfex: 178,
    label: "مكسيما",
    value: "7",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 93,
    idfex: 179,
    label: "مازدا",
    value: "8",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 94,
    idfex: 180,
    label: "تويوتا",
    value: "9",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 95,
    idfex: 181,
    label: "نيسان",
    value: "10",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 96,
    idfex: 182,
    label: "شافروليت",
    value: "11",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 97,
    idfex: 183,
    label: "بي ام دبليو",
    value: "12",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 98,
    idfex: 184,
    label: "ستروين",
    value: "13",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 99,
    idfex: 185,
    label: "كيا",
    value: "14",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 100,
    idfex: 186,
    label: "MG RX 5",
    value: "15",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 101,
    idfex: 187,
    label: "GMC",
    value: "16",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 102,
    idfex: 188,
    label: "تويوتا",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "2",
  },
  {
    id: 103,
    idfex: 189,
    label: "نيسان",
    value: "2",
    asset_Number_class: "4",
    asset_Number_subclass: "2",
  },
  {
    id: 104,
    idfex: 190,
    label: "سوزي",
    value: "3",
    asset_Number_class: "4",
    asset_Number_subclass: "2",
  },
  {
    id: 105,
    idfex: 191,
    label: "متشي بيشي",
    value: "4",
    asset_Number_class: "4",
    asset_Number_subclass: "2",
  },
  {
    id: 106,
    idfex: 192,
    label: "MG T60",
    value: "5",
    asset_Number_class: "4",
    asset_Number_subclass: "2",
  },
  {
    id: 107,
    idfex: 193,
    label: "متشي بيشي",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "3",
  },
  {
    id: 108,
    idfex: 194,
    label: "مازدا",
    value: "2",
    asset_Number_class: "4",
    asset_Number_subclass: "3",
  },
  {
    id: 109,
    idfex: 195,
    label: "تويوتا",
    value: "3",
    asset_Number_class: "4",
    asset_Number_subclass: "3",
  },
  {
    id: 110,
    idfex: 196,
    label: "سوزي",
    value: "4",
    asset_Number_class: "4",
    asset_Number_subclass: "3",
  },
  {
    id: 111,
    idfex: 197,
    label: "كيا",
    value: "5",
    asset_Number_class: "4",
    asset_Number_subclass: "3",
  },
  {
    id: 112,
    idfex: 198,
    label: "هونداي",
    value: "6",
    asset_Number_class: "4",
    asset_Number_subclass: "3",
  },
  {
    id: 113,
    idfex: 199,
    label: "ديلي",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 114,
    idfex: 200,
    label: "تويوتا",
    value: "2",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 115,
    idfex: 201,
    label: "مازدا",
    value: "3",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 116,
    idfex: 202,
    label: "فلكس",
    value: "4",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 117,
    idfex: 203,
    label: "نيسان",
    value: "5",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 118,
    idfex: 204,
    label: "هونداي",
    value: "6",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 119,
    idfex: 205,
    label: "MAN",
    value: "7",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 120,
    idfex: 206,
    label: "مازدا",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "5",
  },
  {
    id: 121,
    idfex: 207,
    label: "فيات",
    value: "2",
    asset_Number_class: "4",
    asset_Number_subclass: "5",
  },
  {
    id: 122,
    idfex: 208,
    label: "ديلي",
    value: "3",
    asset_Number_class: "4",
    asset_Number_subclass: "5",
  },
  {
    id: 123,
    idfex: 209,
    label: "نيسان",
    value: "4",
    asset_Number_class: "4",
    asset_Number_subclass: "5",
  },
  {
    id: 124,
    idfex: 210,
    label: "مياه",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "6",
  },
  {
    id: 125,
    idfex: 211,
    label: "مجاري",
    value: "2",
    asset_Number_class: "4",
    asset_Number_subclass: "6",
  },
  {
    id: 126,
    idfex: 212,
    label: "اسعاف",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "7",
  },
  {
    id: 127,
    idfex: 213,
    label: "رينو",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "8",
  },
  {
    id: 128,
    idfex: 214,
    label: "درجات",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "9",
  },
  {
    id: 129,
    idfex: 215,
    label: "فورد",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "10",
  },
  {
    id: 130,
    idfex: 216,
    label: "الة جلخ",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 131,
    idfex: 217,
    label: "ماكينة لحام",
    value: "2",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 132,
    idfex: 218,
    label: "جهاز شحن بطاريات",
    value: "3",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 133,
    idfex: 219,
    label: "مثقبات",
    value: "4",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 134,
    idfex: 220,
    label: "ضاغط هواء",
    value: "5",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 135,
    idfex: 221,
    label: "كمبريسة",
    value: "6",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 136,
    idfex: 222,
    label: "الة نجارة",
    value: "7",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 137,
    idfex: 223,
    label: "الة قص حديد",
    value: "8",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 138,
    idfex: 224,
    label: "مورصة ثابتة",
    value: "9",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 139,
    idfex: 225,
    label: "الة رفع سيارات",
    value: "10",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 140,
    idfex: 226,
    label: "الة كبس كوابل",
    value: "11",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 141,
    idfex: 227,
    label: "جهاز قياس كهرباء",
    value: "12",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 142,
    idfex: 228,
    label: "الة فك اطارات",
    value: "13",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 143,
    idfex: 229,
    label: "الات خراطة",
    value: "14",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 144,
    idfex: 230,
    label: "مياه",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "2",
  },
  {
    id: 145,
    idfex: 231,
    label: "هواء",
    value: "2",
    asset_Number_class: "5",
    asset_Number_subclass: "2",
  },
  {
    id: 146,
    idfex: 232,
    label: "غسيل",
    value: "3",
    asset_Number_class: "5",
    asset_Number_subclass: "2",
  },
  {
    id: 147,
    idfex: 233,
    label: "تشحيم",
    value: "4",
    asset_Number_class: "5",
    asset_Number_subclass: "2",
  },
  {
    id: 148,
    idfex: 234,
    label: "مقشطة",
    value: "5",
    asset_Number_class: "5",
    asset_Number_subclass: "2",
  },
  {
    id: 149,
    idfex: 235,
    label: "زيت",
    value: "6",
    asset_Number_class: "5",
    asset_Number_subclass: "2",
  },
  {
    id: 150,
    idfex: 236,
    label: "معدات اطفاء",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "3",
  },
  {
    id: 151,
    idfex: 237,
    label: "معدات مكافحة وتشتيت",
    value: "2",
    asset_Number_class: "5",
    asset_Number_subclass: "3",
  },
  {
    id: 152,
    idfex: 238,
    label: "جهاز تعبئة اسطوانات الاطفاء",
    value: "3",
    asset_Number_class: "5",
    asset_Number_subclass: "3",
  },
  {
    id: 153,
    idfex: 239,
    label: "اسطوانات انارة",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "4",
  },
  {
    id: 154,
    idfex: 240,
    label: "مورصة انارة",
    value: "2",
    asset_Number_class: "5",
    asset_Number_subclass: "4",
  },
  {
    id: 155,
    idfex: 241,
    label: "اسطوانات",
    value: "3",
    asset_Number_class: "5",
    asset_Number_subclass: "4",
  },
  {
    id: 156,
    idfex: 242,
    label: "لامبة قاعدة شحن",
    value: "4",
    asset_Number_class: "5",
    asset_Number_subclass: "4",
  },
  {
    id: 157,
    idfex: 243,
    label: "معدات بحرية",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "5",
  },
  {
    id: 158,
    idfex: 244,
    label: "ضاغط هواء 50 لتر",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "6",
  },
  {
    id: 159,
    idfex: 245,
    label: "مزدوج",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "7",
  },
  {
    id: 160,
    idfex: 246,
    label: "متنوعة",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "8",
  },
  {
    id: 161,
    idfex: 247,
    label: "مكتب متكامل",
    value: "1",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 162,
    idfex: 248,
    label: "طاولة مكتب",
    value: "2",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 163,
    idfex: 249,
    label: "طاولة حاسوب",
    value: "3",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 164,
    idfex: 250,
    label: "مكتبة",
    value: "4",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 165,
    idfex: 251,
    label: "اسكفاري سقف معلق",
    value: "5",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 166,
    idfex: 252,
    label: "طاولة اجتماعات",
    value: "6",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 167,
    idfex: 253,
    label: "طاولة اذاعة مرئية",
    value: "7",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 168,
    idfex: 254,
    label: "طاولة ضيافة",
    value: "8",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 169,
    idfex: 255,
    label: "حامل بطاقات كردكس",
    value: "9",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 170,
    idfex: 256,
    label: "باب وشباك",
    value: "10",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 171,
    idfex: 257,
    label: "طاولة الومنيوم",
    value: "11",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 172,
    idfex: 258,
    label: "علبة ادراج متحركة",
    value: "12",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 173,
    idfex: 259,
    label: "مرجع جانبي",
    value: "13",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 174,
    idfex: 260,
    label: "كرسي دوار",
    value: "1",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 175,
    idfex: 261,
    label: "كرسي ضيافة",
    value: "2",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 176,
    idfex: 262,
    label: "كرسي عادي",
    value: "3",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 177,
    idfex: 263,
    label: "كرسي حاسوب",
    value: "4",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 178,
    idfex: 264,
    label: "دولاب عادي",
    value: "5",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 179,
    idfex: 265,
    label: "دولاب سحاب",
    value: "6",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 180,
    idfex: 266,
    label: "صالون",
    value: "7",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 181,
    idfex: 267,
    label: "ثلاجة",
    value: "1",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 182,
    idfex: 268,
    label: "فرن غاز",
    value: "2",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 183,
    idfex: 269,
    label: "ماكينة قهوة",
    value: "3",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 184,
    idfex: 270,
    label: "اذاعة مرئية",
    value: "4",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 185,
    idfex: 271,
    label: "خزنة حديد",
    value: "5",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 186,
    idfex: 272,
    label: "منظومة استقبال مرئي",
    value: "6",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 187,
    idfex: 273,
    label: "مكنسة كهربائية",
    value: "7",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 188,
    idfex: 274,
    label: "الة تنقية مياه",
    value: "8",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 189,
    idfex: 275,
    label: "جهاز فيديو وقاري اقراص",
    value: "9",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 190,
    idfex: 276,
    label: "الة تغليف بطاقات",
    value: "10",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 191,
    idfex: 277,
    label: "كوشة كهربائية",
    value: "11",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 192,
    idfex: 278,
    label: "سرير",
    value: "12",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 193,
    idfex: 279,
    label: "ميزان",
    value: "13",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 194,
    idfex: 280,
    label: "مسجل وراديو",
    value: "14",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 195,
    idfex: 281,
    label: "فرش",
    value: "15",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 196,
    idfex: 282,
    label: "ستائر",
    value: "16",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 197,
    idfex: 283,
    label: "علاقة ملابس",
    value: "17",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 198,
    idfex: 284,
    label: "عادمة ورق",
    value: "18",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 199,
    idfex: 285,
    label: "خلاط فواكة",
    value: "19",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 200,
    idfex: 286,
    label: "سخانة",
    value: "20",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 201,
    idfex: 287,
    label: "الة تلميع احذية",
    value: "21",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 202,
    idfex: 288,
    label: "ساعة حائطية",
    value: "22",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 203,
    idfex: 289,
    label: "حجرة نوم زوجية",
    value: "23",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 204,
    idfex: 290,
    label: "زيانة",
    value: "24",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 205,
    idfex: 291,
    label: "شنفيرة",
    value: "25",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 206,
    idfex: 292,
    label: "حاملة احدية",
    value: "26",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 207,
    idfex: 293,
    label: "طاولة اكل",
    value: "27",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 208,
    idfex: 294,
    label: "كرسي اكل",
    value: "28",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 209,
    idfex: 295,
    label: "مراة",
    value: "29",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 210,
    idfex: 296,
    label: "مكرويف",
    value: "30",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 211,
    idfex: 297,
    label: "سرير طبي",
    value: "1",
    asset_Number_class: "6",
    asset_Number_subclass: "4",
  },
  {
    id: 212,
    idfex: 298,
    label: "كرسي متحرك",
    value: "2",
    asset_Number_class: "6",
    asset_Number_subclass: "4",
  },
  {
    id: 213,
    idfex: 299,
    label: "معدات طبية",
    value: "3",
    asset_Number_class: "6",
    asset_Number_subclass: "4",
  },
  {
    id: 214,
    idfex: 300,
    label: "نقالة مصابين",
    value: "4",
    asset_Number_class: "6",
    asset_Number_subclass: "4",
  },
  {
    id: 215,
    idfex: 301,
    label: "محدوفات",
    value: "1",
    asset_Number_class: "6",
    asset_Number_subclass: "22",
  },
  {
    id: 216,
    idfex: 302,
    label: "معدات لاسلكي",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "1",
  },
  {
    id: 217,
    idfex: 303,
    label: "هواتف",
    value: "2",
    asset_Number_class: "7",
    asset_Number_subclass: "1",
  },
  {
    id: 218,
    idfex: 304,
    label: "نقال وريفي",
    value: "3",
    asset_Number_class: "7",
    asset_Number_subclass: "1",
  },
  {
    id: 219,
    idfex: 305,
    label: "بدالة",
    value: "4",
    asset_Number_class: "7",
    asset_Number_subclass: "1",
  },
  {
    id: 220,
    idfex: 306,
    label: "مقسم",
    value: "5",
    asset_Number_class: "7",
    asset_Number_subclass: "1",
  },
  {
    id: 221,
    idfex: 307,
    label: "هوائية",
    value: "6",
    asset_Number_class: "7",
    asset_Number_subclass: "1",
  },
  {
    id: 222,
    idfex: 308,
    label: "جهاز حاسوب",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 223,
    idfex: 309,
    label: "طابعة حاسوب",
    value: "2",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 224,
    idfex: 310,
    label: "ماسحة ضوئية اسكنر",
    value: "3",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 225,
    idfex: 311,
    label: "فاكس",
    value: "4",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 226,
    idfex: 312,
    label: "الة سحب",
    value: "5",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 227,
    idfex: 313,
    label: "منظم كهرباء",
    value: "6",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 228,
    idfex: 314,
    label: "الة حاسبة",
    value: "7",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 229,
    idfex: 315,
    label: "جهاز عرض بيانات",
    value: "8",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 230,
    idfex: 316,
    label: "الة كاتبة",
    value: "9",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },

  {
    id: 231,
    idfex: 317,
    label: "الة عد نقود",
    value: "10",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 232,
    idfex: 318,
    label: "منظومات",
    value: "11",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 233,
    idfex: 319,
    label: "قارئ اقراص",
    value: "12",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 234,
    idfex: 320,
    label: "قارئ شفرة",
    value: "13",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 235,
    idfex: 321,
    label: "حاسوب محمول",
    value: "14",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 236,
    idfex: 322,
    label: "الة تصوير كاميرا",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 237,
    idfex: 323,
    label: 'الة تصوير "دجتل + فيديو"',
    value: "2",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 238,
    idfex: 324,
    label: "الة تصوير مستندات",
    value: "3",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 239,
    idfex: 325,
    label: "جهاز مرئي",
    value: "4",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 240,
    idfex: 326,
    label: "الة عد نقود",
    value: "5",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 241,
    idfex: 327,
    label: "منظومة استقبال (دجتل)",
    value: "6",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 242,
    idfex: 328,
    label: "مكنسة كهربائية",
    value: "7",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 243,
    idfex: 329,
    label: "معدات رياضية",
    value: "8",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 244,
    idfex: 330,
    label: "جهاز فيديو",
    value: "9",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 245,
    idfex: 331,
    label: "الة تغليف وتجليد",
    value: "10",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 246,
    idfex: 332,
    label: "الة عدمة ورق",
    value: "18",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 247,
    idfex: 333,
    label: "غسالة",
    value: "19",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 248,
    idfex: 334,
    label: "الة تنظيف غبار",
    value: "20",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 249,
    idfex: 335,
    label: "مكيف هواء قطعتين",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "4",
  },
  {
    id: 250,
    idfex: 336,
    label: "مكيف هواء قطعة واحدة",
    value: "2",
    asset_Number_class: "7",
    asset_Number_subclass: "4",
  },
  {
    id: 251,
    idfex: 337,
    label: "مروحة",
    value: "3",
    asset_Number_class: "7",
    asset_Number_subclass: "4",
  },
  {
    id: 252,
    idfex: 338,
    label: "دفاية",
    value: "4",
    asset_Number_class: "7",
    asset_Number_subclass: "4",
  },
  {
    id: 253,
    idfex: 339,
    label: "مكيف مركزي",
    value: "5",
    asset_Number_class: "7",
    asset_Number_subclass: "4",
  },
  {
    id: 254,
    idfex: 340,
    label: "مصاعد",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "5",
  },
  {
    id: 255,
    idfex: 341,
    label: "مصابيح",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "6",
  },
  {
    id: 256,
    idfex: 342,
    label: "معدات طبية",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "7",
  },
  {
    id: 257,
    idfex: 343,
    label: "جهاز البصمة",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "8",
  },
  {
    id: 258,
    idfex: 344,
    label: "منظومة كاميرات",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "9",
  },
  {
    id: 259,
    idfex: 345,
    label: "شاشة حاسوب",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "22",
  },
  {
    id: 260,
    idfex: 346,
    label: "الآراضي",
    value: "1",
    asset_Number_class: "8",
    asset_Number_subclass: "1",
  },

  {
    id: 261,
    idfex: 347,
    label: "معدات الصومعة",
    value: "1",
    asset_Number_class: "9",
    asset_Number_subclass: "1",
  },
  {
    id: 262,
    idfex: 348,
    label: "الارصفة",
    value: "1",
    asset_Number_class: "10",
    asset_Number_subclass: "1",
  },
  {
    id: 263,
    idfex: 349,
    label: "النفطية",
    value: "2",
    asset_Number_class: "10",
    asset_Number_subclass: "1",
  },
  {
    id: 264,
    idfex: 350,
    label: "الخدمية",
    value: "3",
    asset_Number_class: "10",
    asset_Number_subclass: "1",
  },
  {
    id: 265,
    idfex: 351,
    label: "الساحات",
    value: "1",
    asset_Number_class: "11",
    asset_Number_subclass: "1",
  },
  {
    id: 266,
    idfex: 352,
    label: "الطرق",
    value: "1",
    asset_Number_class: "11",
    asset_Number_subclass: "2",
  },
  {
    id: 267,
    idfex: 353,
    label: "الساحات الغير مرصوفة",
    value: "1",
    asset_Number_class: "11",
    asset_Number_subclass: "3",
  },
  {
    id: 268,
    idfex: 354,
    label: "حواجز الامواج",
    value: "1",
    asset_Number_class: "12",
    asset_Number_subclass: "1",
  },
  {
    id: 269,
    idfex: 355,
    label: "حواجز الامواج",
    value: "12",
    asset_Number_class: "12",
    asset_Number_subclass: "12",
  },
  {
    id: 270,
    idfex: 356,
    label: "معدات ومحطات معالجة الصرف الحصحي",
    value: "1",
    asset_Number_class: "13",
    asset_Number_subclass: "1",
  },
  {
    id: 271,
    idfex: 357,
    label: "معدات ومحطات الكهرباء",
    value: "2",
    asset_Number_class: "13",
    asset_Number_subclass: "1",
  },
  {
    id: 272,
    idfex: 358,
    label: "معدات محطة الغسيل",
    value: "3",
    asset_Number_class: "13",
    asset_Number_subclass: "1",
  },
  {
    id: 273,
    idfex: 359,
    label: "محطة تحلية مياه",
    value: "4",
    asset_Number_class: "13",
    asset_Number_subclass: "1",
  },
  {
    id: 274,
    idfex: 360,
    label: "المنظومات",
    value: "1",
    asset_Number_class: "14",
    asset_Number_subclass: "1",
  },
  {
    id: 275,
    idfex: 361,
    label: "المنظومات",
    value: "1",
    asset_Number_class: "14",
    asset_Number_subclass: "14",
  },
  {
    id: 276,
    idfex: 362,
    label: "البرامج",
    value: "2",
    asset_Number_class: "14",
    asset_Number_subclass: "14",
  },
  {
    id: 277,
    idfex: 363,
    label: "الشبكات",
    value: "3",
    asset_Number_class: "14",
    asset_Number_subclass: "14",
  },
  {
    id: 278,
    idfex: 364,
    label: "المخرد",
    value: "1",
    asset_Number_class: "15",
    asset_Number_subclass: "1",
  },
];
