import {
  ChartCandlestick,
  LayoutDashboard,
  TicketSlash,
  SquarePlus,
  Notebook,
  NotebookPen,
} from "lucide-react";
import { AssetNumberClassDetail, AssetNumberDetail, AssetNumberSubclassDetail, AssetStateDetail, AssetValueDetail, NavLinkDetail } from "../Types/Types";

// Your navLinks array with numeric IDs
export const navLinks: NavLinkDetail[] = [
  {
    id: 1,
    label: "لوحة التحكم",
    route: "/",
    icon: LayoutDashboard,
    visible: ["admin"],
  },
  {
    id: 2,
    label: "الاصول",
    route: "/assets",
    icon: ChartCandlestick,
    visible: ["admin"],
  },
  {
    id: 3,
    label: "الجرد",
    route: "/assetInventory",
    icon: TicketSlash,
    visible: ["admin", "user"],
  },
  {
    id: 4,
    label: "اضافة اصل لجرد",
    route: "/assetInventory/new",
    icon: SquarePlus,
    visible: ["admin", "user"],
  },
  {
    id: 5,
    label: "ملاحظات",
    route: "/noteis",
    icon: Notebook,
    visible: ["admin"],
  },
  {
    id: 6,
    label: "اضف ملاحظة",
    route: "/noteis/new",
    icon: NotebookPen,
    visible: ["admin", "noter", "user"],
  },
  // Add more pages as needed
];


export const columnNamesSearch: Record<string, string> = {
  fullName: "اسم الاصل",
  name: "اسم الاصل",
  number:"رقم الاصل",
  assetNumber: "تاغ الاصل",
  tag: "تاغ الاصل",
  place: "مكان الاصل",
  dateUse: "تاريخ استلام الاصل",
  reciever: "مكان التسليم الاصل",
};

// asset_Number_class
export const asset_State: AssetStateDetail[] = [
  { id: 1, label: "مستهلك", value: "مستهلك" },
  { id: 2, label: "جيد", value: "جيد" },
  { id: 3, label: "عاطل", value: "عاطل" },
];

// asset_Value
export const asset_Value: AssetValueDetail[] = [
  { id: 1, label: "0", value: "0" },
  { id: 2, label: "500", value: "500" },
  { id: 3, label: "1000", value: "1000" },
  { id: 4, label: "10000", value: "10000" },
  { id: 5, label: "100000", value: "100000" },
];


// asset_Number_class
export const asset_Number_class: AssetNumberClassDetail[] = [
  { id: 1, label: "المباني", value: "1" },
  { id: 2, label: "المعدات البحرية", value: "2" },
  { id: 3, label: "المعدات البرية", value: "3" },
  { id: 4, label: "وسائل نقل", value: "4" },
  { id: 5, label: "معدات الورش", value: "5" },
  { id: 6, label: "أثاث مكتبي", value: "6" },
  { id: 7, label: "معدات وأدوات مكتبية", value: "7" },
  { id: 8, label: "الأراضي", value: "8" },
  { id: 9, label: "معدات الصومعة", value: "9" },
  { id: 10, label: "الأرصفة", value: "10" },
  { id: 11, label: "الطرق والساحات", value: "11" },
  { id: 12, label: "حواجز الأمواج", value: "12" },
  { id: 13, label: "معدات ومحطات", value: "13" },
  { id: 14, label: "الأصول غير ملموسة", value: "14" },
  { id: 15, label: "المخرد", value: "15" },
];


export const asset_Number_subclass: AssetNumberSubclassDetail[] = [
  // المباني
  { id: 1, label: "المباني", value: "1", asset_Number_class: "1" },
  { id: 2, label: "المنصات", value: "2", asset_Number_class: "1" },
  { id: 3, label: "مصاعد", value: "3", asset_Number_class: "1" },
  { id: 4, label: "الطرق", value: "4", asset_Number_class: "1" },
  { id: 5, label: "شبكات المياه", value: "5", asset_Number_class: "1" },
  { id: 6, label: "الانشاءات", value: "6", asset_Number_class: "1" },
  { id: 9, label: "محطات", value: "9", asset_Number_class: "1" },
  { id: 10, label: "البوابات", value: "10", asset_Number_class: "1" },
  { id: 11, label: "مظلات", value: "11", asset_Number_class: "1" },

  // المعدات البحرية
  { id: 12, label: "القواطر", value: "1", asset_Number_class: "2" },
  { id: 13, label: "الزوارق", value: "2", asset_Number_class: "2" },
  { id: 14, label: "الروافع", value: "3", asset_Number_class: "2" },
  { id: 15, label: "المنارات", value: "4", asset_Number_class: "2" },

  // المعدات البرية
  { id: 16, label: "شوكية", value: "1", asset_Number_class: "3" },
  { id: 17, label: "يدوية", value: "2", asset_Number_class: "3" },
  { id: 18, label: "ارضية", value: "3", asset_Number_class: "3" },
  { id: 19, label: "غرافات", value: "4", asset_Number_class: "3" },
  { id: 20, label: "شفاطات", value: "5", asset_Number_class: "3" },
  { id: 21, label: "جرارات", value: "6", asset_Number_class: "3" },
  { id: 22, label: "مقطورات", value: "7", asset_Number_class: "3" },
  { id: 23, label: "خزانات", value: "8", asset_Number_class: "3" },
  { id: 24, label: "معدات مناولة", value: "9", asset_Number_class: "3" },
  { id: 25, label: "الالات", value: "10", asset_Number_class: "3" },
  { id: 26, label: "الموازين", value: "11", asset_Number_class: "3" },
  { id: 27, label: "محطات كهرباء", value: "12", asset_Number_class: "3" },
  {
    id: 28,
    label: "مدات محطة مالجة ال الحي",
    value: "13",
    asset_Number_class: "3",
  },
  { id: 29, label: "مدات والالاي الومة", value: "14", asset_Number_class: "3" },
  { id: 30, label: "ابراج", value: "15", asset_Number_class: "3" },
  { id: 31, label: "قنطرية", value: "16", asset_Number_class: "3" },
  { id: 32, label: "شاحنات", value: "17", asset_Number_class: "3" },

  // وسائل نقل
  { id: 33, label: "صالون", value: "1", asset_Number_class: "4" },
  { id: 34, label: "نقل مزدوج", value: "2", asset_Number_class: "4" },
  { id: 35, label: "نقل خفيف", value: "3", asset_Number_class: "4" },
  { id: 36, label: "حافلات", value: "4", asset_Number_class: "4" },
  { id: 37, label: "شاحنة بضائع", value: "5", asset_Number_class: "4" },
  { id: 38, label: "ناقلات", value: "6", asset_Number_class: "4" },
  { id: 39, label: "اسعاف", value: "7", asset_Number_class: "4" },
  { id: 40, label: "مطافي", value: "8", asset_Number_class: "4" },
  { id: 41, label: "درجات", value: "9", asset_Number_class: "4" },
  { id: 42, label: "سيارة مجهزة بعدة", value: "10", asset_Number_class: "4" },

  // معدات الورش
  { id: 43, label: "الات ورش", value: "1", asset_Number_class: "5" },
  { id: 44, label: "مضخات", value: "2", asset_Number_class: "5" },
  { id: 45, label: "معدات سلامة", value: "3", asset_Number_class: "5" },
  { id: 46, label: "الانارة", value: "4", asset_Number_class: "5" },
  { id: 47, label: "معدات بحرية", value: "5", asset_Number_class: "5" },
  { id: 48, label: "ضاغط هواء", value: "6", asset_Number_class: "5" },
  { id: 49, label: "سلم", value: "7", asset_Number_class: "5" },
  { id: 50, label: "متنوعة", value: "8", asset_Number_class: "5" },

  // أثاث مكتبي
  { id: 51, label: "المكاتب والمكتبات", value: "1", asset_Number_class: "6" },
  { id: 52, label: "كراسي ودواليب", value: "2", asset_Number_class: "6" },
  { id: 53, label: "اثاث منزلي", value: "3", asset_Number_class: "6" },
  { id: 54, label: "معدات طبية", value: "4", asset_Number_class: "6" },
  { id: 55, label: "محدوفات", value: "22", asset_Number_class: "6" },

  // معدات وأدوات مكتبية
  { id: 56, label: "معدات لاسلكي وهواتف", value: "1", asset_Number_class: "7" },
  { id: 57, label: "حواسيب وفاكسات", value: "2", asset_Number_class: "7" },
  { id: 58, label: "اجهزة ومعدات", value: "3", asset_Number_class: "7" },
  { id: 59, label: "مكيفات", value: "4", asset_Number_class: "7" },
  { id: 60, label: "أثاث", value: "5", asset_Number_class: "7" },

  // الأراضي
  { id: 61, label: "أراضي زراعية", value: "1", asset_Number_class: "8" },
  { id: 62, label: "أراضي سكنية", value: "2", asset_Number_class: "8" },
  { id: 63, label: "أراضي صناعية", value: "3", asset_Number_class: "8" },

  // معدات الصومعة
  { id: 64, label: "صومعة", value: "1", asset_Number_class: "9" },
  { id: 65, label: "أجهزة ومعدات", value: "2", asset_Number_class: "9" },

  // الأرصفة
  { id: 66, label: "أرصفة", value: "1", asset_Number_class: "10" },
  { id: 67, label: "أرصفة مائية", value: "2", asset_Number_class: "10" },

  // الطرق والساحات
  { id: 68, label: "طرق", value: "1", asset_Number_class: "11" },
  { id: 69, label: "ساحات", value: "2", asset_Number_class: "11" },

  // حواجز الأمواج
  { id: 70, label: "حواجز", value: "1", asset_Number_class: "12" },
  { id: 71, label: "أعمدة إنارة", value: "2", asset_Number_class: "12" },

  // مولدات الطاقة
  { id: 72, label: "مولدات", value: "1", asset_Number_class: "13" },
  { id: 73, label: "محولات كهرباء", value: "2", asset_Number_class: "13" },

  // محطات معالجة مياه
  { id: 74, label: "محطات", value: "1", asset_Number_class: "14" },
  { id: 75, label: "خزانات", value: "2", asset_Number_class: "14" },

  // مواقف السيارات
  { id: 76, label: "مواقف سيارات", value: "1", asset_Number_class: "15" },
];

export const asset_Number_detail: AssetNumberDetail[] = [
  {
    id: 1,
    label: "خرسانة",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "1",
  },
  {
    id: 2,
    label: "متنقلة",
    value: "2",
    asset_Number_class: "1",
    asset_Number_subclass: "1",
  },
  {
    id: 3,
    label: "جاهزة",
    value: "3",
    asset_Number_class: "1",
    asset_Number_subclass: "1",
  },
  {
    id: 4,
    label: "سياج",
    value: "4",
    asset_Number_class: "1",
    asset_Number_subclass: "1",
  },
  {
    id: 5,
    label: "مخزن",
    value: "5",
    asset_Number_class: "1",
    asset_Number_subclass: "1",
  },
  {
    id: 6,
    label: "منصات",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "2",
  },
  {
    id: 7,
    label: "مضلات",
    value: "2",
    asset_Number_class: "1",
    asset_Number_subclass: "2",
  },
  {
    id: 8,
    label: "مصعد حمولة 6 أشخاص",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "3",
  },
  {
    id: 9,
    label: "الطرق",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "4",
  },
  {
    id: 10,
    label: "ساحات",
    value: "2",
    asset_Number_class: "1",
    asset_Number_subclass: "4",
  },
  {
    id: 11,
    label: "شبكات مياه",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "5",
  },
  {
    id: 12,
    label: "انشاءات",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "6",
  },
  {
    id: 13,
    label: "ساحات",
    value: "2",
    asset_Number_class: "1",
    asset_Number_subclass: "6",
  },
  {
    id: 14,
    label: "الكهرباء",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "9",
  },
  {
    id: 15,
    label: "الصرف الصحي",
    value: "2",
    asset_Number_class: "1",
    asset_Number_subclass: "9",
  },
  {
    id: 16,
    label: "البوابات",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "10",
  },
  {
    id: 17,
    label: "مظلات بالصاج",
    value: "1",
    asset_Number_class: "1",
    asset_Number_subclass: "11",
  },
  {
    id: 18,
    label: "مضلات قماش",
    value: "2",
    asset_Number_class: "1",
    asset_Number_subclass: "11",
  },
  {
    id: 19,
    label: "قواطر",
    value: "1",
    asset_Number_class: "2",
    asset_Number_subclass: "1",
  },
  {
    id: 20,
    label: "ناقلة مياه",
    value: "2",
    asset_Number_class: "2",
    asset_Number_subclass: "1",
  },
  {
    id: 21,
    label: "ارشاد",
    value: "1",
    asset_Number_class: "2",
    asset_Number_subclass: "2",
  },
  {
    id: 22,
    label: "مسح",
    value: "2",
    asset_Number_class: "2",
    asset_Number_subclass: "2",
  },
  {
    id: 23,
    label: "ربط",
    value: "3",
    asset_Number_class: "2",
    asset_Number_subclass: "2",
  },
  {
    id: 24,
    label: "قوارب",
    value: "4",
    asset_Number_class: "2",
    asset_Number_subclass: "2",
  },
  {
    id: 25,
    label: "روافع",
    value: "1",
    asset_Number_class: "2",
    asset_Number_subclass: "3",
  },
  {
    id: 26,
    label: "منارات",
    value: "1",
    asset_Number_class: "2",
    asset_Number_subclass: "4",
  },
  {
    id: 27,
    label: "منارة بحرية",
    value: "2",
    asset_Number_class: "2",
    asset_Number_subclass: "4",
  },
  {
    id: 28,
    label: "3 طن",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 29,
    label: "7 طن",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 30,
    label: "12 طن",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 31,
    label: "16 طن",
    value: "4",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 32,
    label: "30 طن",
    value: "5",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 33,
    label: "40 طن",
    value: "6",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 34,
    label: "36 طن",
    value: "7",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 35,
    label: "13 طن",
    value: "8",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 36,
    label: "45 طن",
    value: "9",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 37,
    label: "65 طن",
    value: "10",
    asset_Number_class: "3",
    asset_Number_subclass: "1",
  },
  {
    id: 38,
    label: "شوكية",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "2",
  },
  {
    id: 39,
    label: "يدوية",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "2",
  },
  {
    id: 40,
    label: "ارضية",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "2",
  },
  {
    id: 41,
    label: "ونش",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "3",
  },
  {
    id: 42,
    label: "رافعة سلة",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "3",
  },
  {
    id: 43,
    label: "رافعة بالسكة",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "3",
  },
  {
    id: 44,
    label: "حفار",
    value: "4",
    asset_Number_class: "3",
    asset_Number_subclass: "3",
  },
  {
    id: 45,
    label: "تسوية",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "4",
  },
  {
    id: 46,
    label: "حبوب",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "4",
  },
  {
    id: 47,
    label: "محوري",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "4",
  },
  {
    id: 48,
    label: "نيرو",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "5",
  },
  {
    id: 49,
    label: "فيقان",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "5",
  },
  {
    id: 50,
    label: "جرار بضائع",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "6",
  },
  {
    id: 51,
    label: "جرار زراعي",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "6",
  },
  {
    id: 52,
    label: "بطاح",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 53,
    label: "ترابوزة",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 54,
    label: "واطي",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 55,
    label: "ساحة",
    value: "4",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 56,
    label: "زراعي",
    value: "5",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 57,
    label: "مسطح",
    value: "6",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 58,
    label: "صناعي",
    value: "7",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 59,
    label: "محاور عجلات",
    value: "8",
    asset_Number_class: "3",
    asset_Number_subclass: "7",
  },
  {
    id: 60,
    label: "ثابت",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "8",
  },
  {
    id: 61,
    label: "مجرور",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "8",
  },
  {
    id: 62,
    label: "لاقط حاويات",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 63,
    label: "منصة",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 64,
    label: "مساند",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 65,
    label: "ابراقة",
    value: "4",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 66,
    label: "وعاء مناولة",
    value: "5",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 67,
    label: "ملحق رافعة",
    value: "6",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 68,
    label: "متدحرجة",
    value: "7",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 69,
    label: "كماشة مناولة شاحنات",
    value: "8",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 70,
    label: "اقماع",
    value: "9",
    asset_Number_class: "3",
    asset_Number_subclass: "9",
  },
  {
    id: 71,
    label: "متنوعة",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "10",
  },
  {
    id: 72,
    label: "ميزان ارضي",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "11",
  },
  {
    id: 73,
    label: "ميزان",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "11",
  },
  {
    id: 74,
    label: "اثقال معايرة",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "11",
  },
  {
    id: 75,
    label: "مفتاح الي",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "12",
  },
  {
    id: 76,
    label: "محطات",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "12",
  },
  {
    id: 77,
    label: "الف الحي",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "13",
  },
  {
    id: 78,
    label: "مدات والالاي الومة",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "14",
  },
  {
    id: 79,
    label: "كهبائية",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "15",
  },
  {
    id: 80,
    label: "قنطرية",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "16",
  },
  {
    id: 81,
    label: "شاحنة مجهزة بسلة صيانة",
    value: "1",
    asset_Number_class: "3",
    asset_Number_subclass: "17",
  },
  {
    id: 82,
    label: "فيات",
    value: "2",
    asset_Number_class: "3",
    asset_Number_subclass: "17",
  },
  {
    id: 83,
    label: "شاحنة مزودة بخزان",
    value: "3",
    asset_Number_class: "3",
    asset_Number_subclass: "17",
  },
  {
    id: 84,
    label: "شاحنة بصندوق قلاب",
    value: "4",
    asset_Number_class: "3",
    asset_Number_subclass: "17",
  },
  {
    id: 85,
    label: "شاحنة افيكوا مع منظومة شفط",
    value: "5",
    asset_Number_class: "3",
    asset_Number_subclass: "17",
  },
  {
    id: 86,
    label: "هونداي",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 87,
    label: "داوو",
    value: "2",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 88,
    label: "صني",
    value: "3",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 89,
    label: "بيجو",
    value: "4",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 90,
    label: "متشي بيشي",
    value: "5",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 91,
    label: "باصات",
    value: "6",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 92,
    label: "مكسيما",
    value: "7",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 93,
    label: "مازدا",
    value: "8",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 94,
    label: "تويوتا",
    value: "9",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 95,
    label: "نيسان",
    value: "10",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 96,
    label: "شافروليت",
    value: "11",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 97,
    label: "بي ام دبليو",
    value: "12",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 98,
    label: "ستروين",
    value: "13",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 99,
    label: "كيا",
    value: "14",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 100,
    label: "MG RX 5",
    value: "15",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 101,
    label: "GMC",
    value: "16",
    asset_Number_class: "4",
    asset_Number_subclass: "1",
  },
  {
    id: 102,
    label: "تويوتا",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "2",
  },
  {
    id: 103,
    label: "نيسان",
    value: "2",
    asset_Number_class: "4",
    asset_Number_subclass: "2",
  },
  {
    id: 104,
    label: "سوزي",
    value: "3",
    asset_Number_class: "4",
    asset_Number_subclass: "2",
  },
  {
    id: 105,
    label: "متشي بيشي",
    value: "4",
    asset_Number_class: "4",
    asset_Number_subclass: "2",
  },
  {
    id: 106,
    label: "MG T60",
    value: "5",
    asset_Number_class: "4",
    asset_Number_subclass: "2",
  },
  {
    id: 107,
    label: "متشي بيشي",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "3",
  },
  {
    id: 108,
    label: "مازدا",
    value: "2",
    asset_Number_class: "4",
    asset_Number_subclass: "3",
  },
  {
    id: 109,
    label: "تويوتا",
    value: "3",
    asset_Number_class: "4",
    asset_Number_subclass: "3",
  },
  {
    id: 110,
    label: "سوزي",
    value: "4",
    asset_Number_class: "4",
    asset_Number_subclass: "3",
  },
  {
    id: 111,
    label: "كيا",
    value: "5",
    asset_Number_class: "4",
    asset_Number_subclass: "3",
  },
  {
    id: 112,
    label: "هونداي",
    value: "6",
    asset_Number_class: "4",
    asset_Number_subclass: "3",
  },
  {
    id: 113,
    label: "ديلي",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 114,
    label: "تويوتا",
    value: "2",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 115,
    label: "مازدا",
    value: "3",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 116,
    label: "فلكس",
    value: "4",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 117,
    label: "نيسان",
    value: "5",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 118,
    label: "هونداي",
    value: "6",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 119,
    label: "MAN",
    value: "7",
    asset_Number_class: "4",
    asset_Number_subclass: "4",
  },
  {
    id: 120,
    label: "مازدا",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "5",
  },
  {
    id: 121,
    label: "فيات",
    value: "2",
    asset_Number_class: "4",
    asset_Number_subclass: "5",
  },
  {
    id: 122,
    label: "ديلي",
    value: "3",
    asset_Number_class: "4",
    asset_Number_subclass: "5",
  },
  {
    id: 123,
    label: "نيسان",
    value: "4",
    asset_Number_class: "4",
    asset_Number_subclass: "5",
  },
  {
    id: 124,
    label: "مياه",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "6",
  },
  {
    id: 125,
    label: "مجاري",
    value: "2",
    asset_Number_class: "4",
    asset_Number_subclass: "6",
  },
  {
    id: 126,
    label: "اسعاف",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "7",
  },
  {
    id: 127,
    label: "رينو",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "8",
  },
  {
    id: 128,
    label: "درجات",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "9",
  },
  {
    id: 129,
    label: "فورد",
    value: "1",
    asset_Number_class: "4",
    asset_Number_subclass: "10",
  },
  {
    id: 130,
    label: "الة جلخ",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 131,
    label: "ماكينة لحام",
    value: "2",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 132,
    label: "جهاز شحن بطاريات",
    value: "3",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 133,
    label: "مثقبات",
    value: "4",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 134,
    label: "ضاغط هواء",
    value: "5",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 135,
    label: "كمبريسة",
    value: "6",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 136,
    label: "الة نجارة",
    value: "7",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 137,
    label: "الة قص حديد",
    value: "8",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 138,
    label: "مورصة ثابتة",
    value: "9",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 139,
    label: "الة رفع سيارات",
    value: "10",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 140,
    label: "الة كبس كوابل",
    value: "11",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 141,
    label: "جهاز قياس كهرباء",
    value: "12",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 142,
    label: "الة فك اطارات",
    value: "13",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 143,
    label: "الات خراطة",
    value: "14",
    asset_Number_class: "5",
    asset_Number_subclass: "1",
  },
  {
    id: 144,
    label: "مياه",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "2",
  },
  {
    id: 145,
    label: "هواء",
    value: "2",
    asset_Number_class: "5",
    asset_Number_subclass: "2",
  },
  {
    id: 146,
    label: "غسيل",
    value: "3",
    asset_Number_class: "5",
    asset_Number_subclass: "2",
  },
  {
    id: 147,
    label: "تشحيم",
    value: "4",
    asset_Number_class: "5",
    asset_Number_subclass: "2",
  },
  {
    id: 148,
    label: "مقشطة",
    value: "5",
    asset_Number_class: "5",
    asset_Number_subclass: "2",
  },
  {
    id: 149,
    label: "زيت",
    value: "6",
    asset_Number_class: "5",
    asset_Number_subclass: "2",
  },
  {
    id: 150,
    label: "معدات اطفاء",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "3",
  },
  {
    id: 151,
    label: "معدات مكافحة وتشتيت",
    value: "2",
    asset_Number_class: "5",
    asset_Number_subclass: "3",
  },
  {
    id: 152,
    label: "جهاز تعبئة اسطوانات الاطفاء",
    value: "3",
    asset_Number_class: "5",
    asset_Number_subclass: "3",
  },
  {
    id: 153,
    label: "اسطوانات انارة",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "4",
  },
  {
    id: 154,
    label: "مورصة انارة",
    value: "2",
    asset_Number_class: "5",
    asset_Number_subclass: "4",
  },
  {
    id: 155,
    label: "اسطوانات",
    value: "3",
    asset_Number_class: "5",
    asset_Number_subclass: "4",
  },
  {
    id: 156,
    label: "لامبة قاعدة شحن",
    value: "4",
    asset_Number_class: "5",
    asset_Number_subclass: "4",
  },
  {
    id: 157,
    label: "معدات بحرية",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "5",
  },
  {
    id: 158,
    label: "ضاغط هواء 50 لتر",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "6",
  },
  {
    id: 159,
    label: "مزدوج",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "7",
  },
  {
    id: 160,
    label: "متنوعة",
    value: "1",
    asset_Number_class: "5",
    asset_Number_subclass: "8",
  },
  {
    id: 161,
    label: "مكتب متكامل",
    value: "1",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 162,
    label: "طاولة مكتب",
    value: "2",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 163,
    label: "طاولة حاسوب",
    value: "3",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 164,
    label: "مكتبة",
    value: "4",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 165,
    label: "اسكفاري سقف معلق",
    value: "5",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 166,
    label: "طاولة اجتماعات",
    value: "6",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 167,
    label: "طاولة اذاعة مرئية",
    value: "7",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 168,
    label: "طاولة ضيافة",
    value: "8",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 169,
    label: "حامل بطاقات كردكس",
    value: "9",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 170,
    label: "باب وشباك",
    value: "10",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 171,
    label: "طاولة الومنيوم",
    value: "11",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 172,
    label: "علبة ادراج متحركة",
    value: "12",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 173,
    label: "مرجع جانبي",
    value: "13",
    asset_Number_class: "6",
    asset_Number_subclass: "1",
  },
  {
    id: 174,
    label: "كرسي دوار",
    value: "1",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 175,
    label: "كرسي ضيافة",
    value: "2",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 176,
    label: "كرسي عادي",
    value: "3",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 177,
    label: "كرسي حاسوب",
    value: "4",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 178,
    label: "دولاب عادي",
    value: "5",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 179,
    label: "دولاب سحاب",
    value: "6",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 180,
    label: "صالون",
    value: "7",
    asset_Number_class: "6",
    asset_Number_subclass: "2",
  },
  {
    id: 181,
    label: "ثلاجة",
    value: "1",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 182,
    label: "فرن غاز",
    value: "2",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 183,
    label: "ماكينة قهوة",
    value: "3",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 184,
    label: "اذاعة مرئية",
    value: "4",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 185,
    label: "خزنة حديد",
    value: "5",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 186,
    label: "منظومة استقبال مرئي",
    value: "6",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 187,
    label: "مكنسة كهربائية",
    value: "7",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 188,
    label: "الة تنقية مياه",
    value: "8",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 189,
    label: "جهاز فيديو وقاري اقراص",
    value: "9",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 190,
    label: "الة تغليف بطاقات",
    value: "10",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 191,
    label: "كوشة كهربائية",
    value: "11",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 192,
    label: "سرير",
    value: "12",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 193,
    label: "ميزان",
    value: "13",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 194,
    label: "مسجل وراديو",
    value: "14",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 195,
    label: "فرش",
    value: "15",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 196,
    label: "ستائر",
    value: "16",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 197,
    label: "علاقة ملابس",
    value: "17",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 198,
    label: "عادمة ورق",
    value: "18",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 199,
    label: "خلاط فواكة",
    value: "19",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 200,
    label: "سخانة",
    value: "20",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 201,
    label: "الة تلميع احذية",
    value: "21",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 202,
    label: "ساعة حائطية",
    value: "22",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 203,
    label: "حجرة نوم زوجية",
    value: "23",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 204,
    label: "زيانة",
    value: "24",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 205,
    label: "شنفيرة",
    value: "25",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 206,
    label: "حاملة احدية",
    value: "26",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 207,
    label: "طاولة اكل",
    value: "27",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 208,
    label: "كرسي اكل",
    value: "28",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 209,
    label: "مراة",
    value: "29",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 210,
    label: "مكرويف",
    value: "30",
    asset_Number_class: "6",
    asset_Number_subclass: "3",
  },
  {
    id: 211,
    label: "سرير طبي",
    value: "1",
    asset_Number_class: "6",
    asset_Number_subclass: "4",
  },
  {
    id: 212,
    label: "كرسي متحرك",
    value: "2",
    asset_Number_class: "6",
    asset_Number_subclass: "4",
  },
  {
    id: 213,
    label: "معدات طبية",
    value: "3",
    asset_Number_class: "6",
    asset_Number_subclass: "4",
  },
  {
    id: 214,
    label: "نقالة مصابين",
    value: "4",
    asset_Number_class: "6",
    asset_Number_subclass: "4",
  },
  {
    id: 215,
    label: "محدوفات",
    value: "1",
    asset_Number_class: "6",
    asset_Number_subclass: "22",
  },
  {
    id: 216,
    label: "معدات لاسلكي",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "1",
  },
  {
    id: 217,
    label: "هواتف",
    value: "2",
    asset_Number_class: "7",
    asset_Number_subclass: "1",
  },
  {
    id: 218,
    label: "نقال وريفي",
    value: "3",
    asset_Number_class: "7",
    asset_Number_subclass: "1",
  },
  {
    id: 219,
    label: "بدالة",
    value: "4",
    asset_Number_class: "7",
    asset_Number_subclass: "1",
  },
  {
    id: 220,
    label: "مقسم",
    value: "5",
    asset_Number_class: "7",
    asset_Number_subclass: "1",
  },
  {
    id: 221,
    label: "هوائية",
    value: "6",
    asset_Number_class: "7",
    asset_Number_subclass: "1",
  },
  {
    id: 222,
    label: "جهاز حاسوب",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 223,
    label: "طابعة حاسوب",
    value: "2",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 224,
    label: "ماسحة ضوئية اسكنر",
    value: "3",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 225,
    label: "فاكس",
    value: "4",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 226,
    label: "الة سحب",
    value: "5",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 227,
    label: "منظم كهرباء",
    value: "6",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 228,
    label: "الة حاسبة",
    value: "7",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 229,
    label: "جهاز عرض بيانات",
    value: "8",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 230,
    label: "الة كاتبة",
    value: "9",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 231,
    label: "الة عد نقود",
    value: "10",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 232,
    label: "منظومات",
    value: "11",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 233,
    label: "قارئ اقراص",
    value: "12",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 234,
    label: "قارئ شفرة",
    value: "13",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 235,
    label: "حاسوب محمول",
    value: "14",
    asset_Number_class: "7",
    asset_Number_subclass: "2",
  },
  {
    id: 236,
    label: "الة تصوير كاميرا",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 237,
    label: 'الة تصوير "دجتل + فيديو"',
    value: "2",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 238,
    label: "الة تصوير مستندات",
    value: "3",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 239,
    label: "جهاز مرئي",
    value: "4",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 240,
    label: "الة عد نقود",
    value: "5",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 241,
    label: "منظومة استقبال (دجتل)",
    value: "6",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 242,
    label: "مكنسة كهربائية",
    value: "7",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 243,
    label: "معدات رياضية",
    value: "8",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 244,
    label: "جهاز فيديو",
    value: "9",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 245,
    label: "الة تغليف وتجليد",
    value: "10",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 246,
    label: "الة عدمة ورق",
    value: "18",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 247,
    label: "غسالة",
    value: "19",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 248,
    label: "الة تنظيف غبار",
    value: "20",
    asset_Number_class: "7",
    asset_Number_subclass: "3",
  },
  {
    id: 249,
    label: "مكيف هواء قطعتين",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "4",
  },
  {
    id: 250,
    label: "مكيف هواء قطعة واحدة",
    value: "2",
    asset_Number_class: "7",
    asset_Number_subclass: "4",
  },
  {
    id: 251,
    label: "مروحة",
    value: "3",
    asset_Number_class: "7",
    asset_Number_subclass: "4",
  },
  {
    id: 252,
    label: "دفاية",
    value: "4",
    asset_Number_class: "7",
    asset_Number_subclass: "4",
  },
  {
    id: 253,
    label: "مكيف مركزي",
    value: "5",
    asset_Number_class: "7",
    asset_Number_subclass: "4",
  },
  {
    id: 254,
    label: "مصاعد",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "5",
  },
  {
    id: 255,
    label: "مصابيح",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "6",
  },
  {
    id: 256,
    label: "معدات طبية",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "7",
  },
  {
    id: 257,
    label: "جهاز البصمة",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "8",
  },
  {
    id: 258,
    label: "منظومة كاميرات",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "9",
  },
  {
    id: 259,
    label: "شاشة حاسوب",
    value: "1",
    asset_Number_class: "7",
    asset_Number_subclass: "22",
  },
  {
    id: 260,
    label: "الآراضي",
    value: "1",
    asset_Number_class: "8",
    asset_Number_subclass: "1",
  },
  {
    id: 261,
    label: "معدات الصومعة",
    value: "1",
    asset_Number_class: "9",
    asset_Number_subclass: "1",
  },
  {
    id: 262,
    label: "الارصفة",
    value: "1",
    asset_Number_class: "10",
    asset_Number_subclass: "1",
  },
  {
    id: 263,
    label: "النفطية",
    value: "2",
    asset_Number_class: "10",
    asset_Number_subclass: "1",
  },
  {
    id: 264,
    label: "الخدمية",
    value: "3",
    asset_Number_class: "10",
    asset_Number_subclass: "1",
  },
  {
    id: 265,
    label: "الساحات",
    value: "1",
    asset_Number_class: "11",
    asset_Number_subclass: "1",
  },
  {
    id: 266,
    label: "الطرق",
    value: "1",
    asset_Number_class: "11",
    asset_Number_subclass: "2",
  },
  {
    id: 267,
    label: "الساحات الغير مرصوفة",
    value: "1",
    asset_Number_class: "11",
    asset_Number_subclass: "3",
  },
  {
    id: 268,
    label: "حواجز الامواج",
    value: "1",
    asset_Number_class: "12",
    asset_Number_subclass: "1",
  },
  {
    id: 269,
    label: "حواجز الامواج",
    value: "12",
    asset_Number_class: "12",
    asset_Number_subclass: "12",
  },
  {
    id: 270,
    label: "معدات ومحطات معالجة الصرف الحصحي",
    value: "1",
    asset_Number_class: "13",
    asset_Number_subclass: "1",
  },
  {
    id: 271,
    label: "معدات ومحطات الكهرباء",
    value: "2",
    asset_Number_class: "13",
    asset_Number_subclass: "1",
  },
  {
    id: 272,
    label: "معدات محطة الغسيل",
    value: "3",
    asset_Number_class: "13",
    asset_Number_subclass: "1",
  },
  {
    id: 273,
    label: "محطة تحلية مياه",
    value: "4",
    asset_Number_class: "13",
    asset_Number_subclass: "1",
  },
  {
    id: 274,
    label: "المنظومات",
    value: "1",
    asset_Number_class: "14",
    asset_Number_subclass: "1",
  },
  {
    id: 275,
    label: "المنظومات",
    value: "1",
    asset_Number_class: "14",
    asset_Number_subclass: "14",
  },
  {
    id: 276,
    label: "البرامج",
    value: "2",
    asset_Number_class: "14",
    asset_Number_subclass: "14",
  },
  {
    id: 277,
    label: "الشبكات",
    value: "3",
    asset_Number_class: "14",
    asset_Number_subclass: "14",
  },
  {
    id: 278,
    label: "المخرد",
    value: "1",
    asset_Number_class: "15",
    asset_Number_subclass: "1",
  },
];